baseURL = 'https://paigeturnertg.github.io/'
languageCode = 'en-us'
title = 'Paige Turner'
theme = 'anatole'

[params]
title = "Paige Turner"
author = "Paige Turner"
description = "Transformation-focused TG fiction"
profilePicture = "images/profile.jpg"
mainSections = ["posts"]

[[params.socialIcons]]
icon = "fab fa-discord"
title = "Discord"
url = "https://discord.gg/w8ne2f7nX8"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:paigeturnertg@gmail.com"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"
  [[menu.main]]
    name = "About"
    weight = 300
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Stories"
    weight = 200
    identifier = "stories"
    url = "/portfolio/"
  [[menu.main]]
    name = "Downloads"
    weight = 400
    identifier = "downloads"
    url = "/downloads/"
  [[menu.main]]
    name = "Discord"
    weight = 500
    identifier = "discord"
    url = "https://discord.gg/w8ne2f7nX8"